import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/">재귀가 뭐죠?</Link>
        <Link href="/Use_Class">현 별 인구 추이</Link>
        <Link href="/Use_Function">현 별 인구 추이(구현중)</Link>
        <Link href="/MapBox_Tutorial">전국 추이</Link>
      </main>
    </div>
  )
}
